name: Test checks access

env:
  bashPass: \033[32;1mPASSED -
  bashInfo: \033[33;1mINFO -
  bashFail: \033[31;1mFAILED -
  bashEnd:  \033[0m

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  git-secrets:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::241411971030:role/GithubOIDCrole
      - name: Add file to s3
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Hello world" > temp.txt
          aws s3 cp temp.txt s3://bucket123456tobedeleted/${{ github.repository }}/
          
        
